CREATE TABLE IF NOT EXISTS books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    published_date DATE,
    pages INTEGER DEFAULT 0,
    genre VARCHAR(100),
    rating FLOAT DEFAULT 0
);
